//! Public types shared across all Transmitter sub-modules.

// ── Clock ─────────────────────────────────────────────────────────────────────

pub trait Clock: Send + Sync {
    fn now_us(&self) -> u64;
}

// ── Packet payload ────────────────────────────────────────────────────────────

/// Opaque byte payload.  Real packets carry actual data; cover packets carry
/// PRNG-generated bytes.  The Transmitter never inspects contents.
pub struct PacketPayload(pub Vec<u8>);

// ── Flow type ─────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FlowType {
    Real,
    Shadow,
}

// ── Input / output packet types ───────────────────────────────────────────────

pub struct RealPacket {
    pub flow_id: u64,
    pub payload_size_bytes: u16,
    pub arrival_timestamp_us: u64,
    pub payload: PacketPayload,
}

pub struct ScheduledPacket {
    pub path_id: u64,
    pub flow_type: FlowType,
    pub payload: PacketPayload,
    pub deadline_us: u64,
    pub sequence_id: u64,
}

// ── Shadow slot (internal, generated by ShadowSyncEngine) ────────────────────

pub struct ShadowSlot {
    /// Relative delay from "now" (when the triggering real packet arrived).
    pub offset_us: u32,
    pub size_bytes: u16,
    pub is_burst_head: bool,
}

// ── Path events (adapter → Transmitter) ──────────────────────────────────────

pub enum PathEvent {
    RttSample {
        path_id: u64,
        rtt_ms: u32,
    },
    PacketLost {
        path_id: u64,
    },
    PacketAcked {
        path_id: u64,
    },
    BandwidthEstimate {
        path_id: u64,
        available_kbps: u32,
    },
    PathDown {
        path_id: u64,
    },
    PathRestored {
        path_id: u64,
        rtt_ms: u32,
        available_kbps: u32,
    },
}

// ── Plan invalidation ─────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct PathStats {
    pub path_id: u64,
    pub rtt_ms: u32,
    pub loss_pct: f32,
    pub available_kbps: u32,
}

#[derive(Debug, Clone)]
pub enum InvalidationReason {
    PathDown { path_id: u64 },
    LatencyExceeded { path_id: u64, observed_rtt_ms: u32 },
    BandwidthShrunk { path_id: u64, available_kbps: u32 },
    AllPathsDegraded,
}

#[derive(Debug, Clone)]
pub struct PlanInvalidationEvent {
    pub reason: InvalidationReason,
    /// `None` means all paths.
    pub affected_path: Option<u64>,
    pub current_stats: PathStats,
}

// ── Configuration ─────────────────────────────────────────────────────────────

pub struct TransmitterConfig {
    pub latency_guard_ms: u32,
    /// Seconds of flow inactivity before statistical model resets (default 30).
    pub idle_timeout_s: u32,
    /// IAT below this → BURST state (μs, default 500).
    pub burst_threshold_us: u32,
    /// IAT above this → IDLE state (μs, default 5000).
    pub idle_threshold_us: u32,
    /// Jitter as fraction of EWMA_IAT (default 0.20).
    pub jitter_iat_ratio: f32,
}

impl Default for TransmitterConfig {
    fn default() -> Self {
        Self {
            latency_guard_ms: 80,
            idle_timeout_s: 30,
            burst_threshold_us: 500,
            idle_threshold_us: 5000,
            jitter_iat_ratio: 0.20,
        }
    }
}

// ── Statistics ────────────────────────────────────────────────────────────────

pub struct PathQueueStats {
    pub path_id: u64,
    pub real_queue_depth: usize,
    pub cover_queue_depth: usize,
    pub token_fill_bits: u64,
    pub suppressed_by_loss: bool,
}

pub struct TransmitterStats {
    pub per_path: Vec<PathQueueStats>,
    pub shadow_slots_dropped: u64,
    pub real_packets_dispatched: u64,
}

// ── Sink error ────────────────────────────────────────────────────────────────

pub enum SendError {
    DeadlineMissed { path_id: u64, late_by_us: u64 },
    PathUnavailable { path_id: u64 },
    QueueFull { path_id: u64 },
}
